cmake_minimum_required(VERSION 2.8)
project(Mandelbrot)

set(PROJECT_VERSION_MAJOR 1)
set(PROJECT_VERSION_MINOR 0)
set(PROJECT_VERSION_PATCH 0)
set(DEBUG 1)
set(USE_OPENMP 1)
set(USE_MB_XY_GRID 1)
set(GRID 1)
set(PROJECT_DEFINE_GRID_STEP_PIXEL 50)
set(PROJECT_DEFINE_GRID_STEP_SIZE 5)
set(TEXT 1)
set(PROJECT_DEFINE_TEXT_OFFSET_X 5)
set(PROJECT_DEFINE_TEXT_OFFSET_Y 5)
set(PROJECT_DEFINE_COLOR_MIN 1)
set(PROJECT_DEFINE_COLOR_MAX 255)

#set(CMAKE_C_COMPILER "/usr/local/bin/gcc")
set(CMAKE_C_FLAGS "-Wall -O3 -funroll-loops -fopenmp")
#set(CMAKE_CXX_COMPILER "/usr/local/bin/g++")
set(CMAKE_CXX_FLAGS ${CMAKE_C_FLAGS})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/bin)
set(CMAKE_MODULE_PATH "${PROJECT_SOURCE_DIR}/lib")

if(${CMAKE_C_COMPILER_ID} MATCHES "Clang" OR ${CMAKE_CXX_COMPILER_ID} MATCHES "Clang")
	set(USE_OPENMP Off)
endif()
if(DEBUG)
	set(PROJECT_DEFINE_DEBUG "#define DEBUG")
endif()
if(USE_OPENMP)
	set(PROJECT_DEFINE_USE_OPENMP "#define USE_OPENMP")
endif()
if(USE_MB_XY_GRID)
	set(PROJECT_DEFINE_USE_MB_XY_GRID "#define USE_MB_XY_GRID")
endif()
if(GRID)
	set(PROJECT_DEFINE_GRID "#define GRID")
endif()
if(TEXT)
	set(PROJECT_DEFINE_TEXT "#define TEXT")
endif()
configure_file("${PROJECT_SOURCE_DIR}/src/config.h.in" "${PROJECT_SOURCE_DIR}/src/config.h" NEWLINE_STYLE LF)



file(GLOB_RECURSE PROJECT_SOURCES "src/*.c" "src/*.cpp")
file(GLOB_RECURSE PROJECT_HEADERS "src/*.h")

set(PROJECT_INCLUDE_DIRS "")
foreach(_headerFile ${PROJECT_HEADERS})
	get_filename_component(_dir ${_headerFile} PATH)
	list(APPEND PROJECT_INCLUDE_DIRS ${_dir})
endforeach()
list(REMOVE_DUPLICATES PROJECT_INCLUDE_DIRS)

find_package(Imlib REQUIRED)
find_package(OpenMP REQUIRED)

include_directories(${PROJECT_INCLUDE_DIRS})

# Imlib2 includes
include_directories(${X11_X11_INCLUDE_PATH})
include_directories(${Imlib_INCLUDE_DIRS})

# OpenMP includes
include_directories(${OpenMP_INCLUDE_DIRS})



#add_definitions(-v)
if(USE_OPENMP)
	add_definitions(-fopenmp)
endif()

add_executable(mandelbrot ${PROJECT_SOURCES})
target_link_libraries(mandelbrot ${Imlib_LIBRARIES})
target_link_libraries(mandelbrot ${OpenMP_LIBRARIES})

add_executable(mandelbrot_test tests/mandelbrot_test.cpp)
target_link_libraries(mandelbrot_test ${Imlib_LIBRARIES})
target_link_libraries(mandelbrot_test ${OpenMP_LIBRARIES})


enable_testing()

add_test(NAME StdRuns COMMAND mandelbrot)
set_tests_properties(StdRuns PROPERTIES WILL_FAIL true)

add_test(NAME TestRuns COMMAND mandelbrot_test)

if(USE_OPENMP)
	add_test(NAME TestOmp1 COMMAND mandelbrot_test)
	set_tests_properties(TestOmp1 PROPERTIES PASS_REGULAR_EXPRESSION "omp_set_num_threads: 0x")

	add_test(NAME TestOmp2 COMMAND mandelbrot_test)
	set_tests_properties(TestOmp2 PROPERTIES PASS_REGULAR_EXPRESSION "omp_get_num_threads: 0x")

	add_test(NAME TestOmp3 COMMAND mandelbrot_test)
	set_tests_properties(TestOmp3 PROPERTIES PASS_REGULAR_EXPRESSION "omp_get_thread_num: 0x")

	add_test(NAME TestOmp4 COMMAND mandelbrot_test)
	set_tests_properties(TestOmp4 PROPERTIES PASS_REGULAR_EXPRESSION "OMP i=[0-9] ID=[1-9]")
endif()

#MESSAGE(STATUS "cmake version: ${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}.${CMAKE_PATCH_VERSION}")
#MESSAGE(STATUS "PROJECT_SOURCE_DIR: '${PROJECT_SOURCE_DIR}'")
#MESSAGE(STATUS "PROJECT_BINARY_DIR: '${PROJECT_BINARY_DIR}'")
#MESSAGE("")

#MESSAGE(STATUS "PROJECT_NAME: '${PROJECT_NAME}'")
#MESSAGE(STATUS "PROJECT_SOURCE_DIR: '${PROJECT_SOURCE_DIR}'")
#MESSAGE(STATUS "PROJECT_BINARY_DIR: '${PROJECT_BINARY_DIR}'")
#MESSAGE("")

#MESSAGE(STATUS "Imlib_FOUND: '${Imlib_FOUND}'")
#MESSAGE(STATUS "Imlib_INCLUDE_DIRS: '${Imlib_INCLUDE_DIRS}'")
#MESSAGE(STATUS "Imlib_LIBRARIES: '${Imlib_LIBRARIES}'")
#MESSAGE(STATUS "Imlib_DEFINITIONS: '${Imlib_DEFINITIONS}'")
#MESSAGE("")

#MESSAGE(STATUS "OpenMP_FOUND: '${OpenMP_FOUND}'")
#MESSAGE(STATUS "OpenMP_INCLUDE_DIRS: '${OpenMP_INCLUDE_DIRS}'")
#MESSAGE(STATUS "OpenMP_LIBRARIES: '${OpenMP_LIBRARIES}'")
#MESSAGE(STATUS "OpenMP_DEFINITIONS: '${OpenMP_DEFINITIONS}'")
#MESSAGE("")

#MESSAGE(STATUS "CMAKE_C_COMPILER: '${CMAKE_C_COMPILER}'")
#MESSAGE(STATUS "CMAKE_C_FLAGS: '${CMAKE_C_FLAGS}'")
#MESSAGE(STATUS "CMAKE_C_FLAGS_DEBUG_INIT: '${CMAKE_C_FLAGS_DEBUG_INIT}'")
#MESSAGE("")

#MESSAGE(STATUS "CMAKE_CXX_COMPILER: '${CMAKE_CXX_COMPILER}'")
#MESSAGE(STATUS "CMAKE_CXX_FLAGS: '${CMAKE_CXX_FLAGS}'")
#MESSAGE(STATUS "CMAKE_CXX_FLAGS_DEBUG_INIT: '${CMAKE_CXX_FLAGS_DEBUG_INIT}'")
#MESSAGE("")

#MESSAGE(STATUS "CMAKE_PREFIX_PATH: '${CMAKE_PREFIX_PATH}'")
#MESSAGE(STATUS "CMAKE_MODULE_PATH: '${CMAKE_MODULE_PATH}'")
#MESSAGE(STATUS "CMAKE_BINARY_DIR: '${CMAKE_BINARY_DIR}'")
#MESSAGE(STATUS "CMAKE_BUILD_TYPE: '${CMAKE_BUILD_TYPE}'")
#MESSAGE(STATUS "CMAKE_RUNTIME_OUTPUT_DIRECTORY: '${CMAKE_RUNTIME_OUTPUT_DIRECTORY}'")
#MESSAGE(STATUS "CMAKE_COMMAND: '${CMAKE_COMMAND}'")
#MESSAGE(STATUS "CMAKE_CONFIGURATION_TYPES: '${CMAKE_CONFIGURATION_TYPES}'")
#MESSAGE(STATUS "CMAKE_FRAMEWORK_PATH: '${CMAKE_FRAMEWORK_PATH}'")
#MESSAGE(STATUS "CMAKE_APPBUNDLE_PATH: '${CMAKE_APPBUNDLE_PATH}'")
#MESSAGE(STATUS "CMAKE_SYSTEM_PREFIX_PATH: '${CMAKE_APPBUNDLE_PATH}'")
#MESSAGE(STATUS "CMAKE_SYSTEM_FRAMEWORK_PATH: '${CMAKE_SYSTEM_FRAMEWORK_PATH}'")
#MESSAGE(STATUS "CMAKE_SYSTEM_APPBUNDLE_PATH: '${CMAKE_SYSTEM_APPBUNDLE_PATH}'")
#MESSAGE("")
